import { useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { lxpApiGetLearningPath, lxpApiListProgress } from '../generated/sdk.gen'
import { client } from '../generated/client.gen'
import ContentViewerModal from './ContentViewerModal'

interface LearningPathDetailModalProps {
  pathId: number
  onClose: () => void
}

export default function LearningPathDetailModal({ pathId, onClose }: LearningPathDetailModalProps) {
  const [selectedContentId, setSelectedContentId] = useState<number | null>(null)
  // Configure client
  client.setConfig({ baseUrl: 'http://localhost:8000' })

  // Fetch learning path details
  const { data: path, isLoading: pathLoading } = useQuery({
    queryKey: ['learning-path', pathId],
    queryFn: async () => {
      const response = await lxpApiGetLearningPath({ path: { path_id: pathId } })
      return response.data
    },
  })

  // Fetch progress for this learning path
  const { data: progressData, isLoading: progressLoading } = useQuery({
    queryKey: ['progress', 'path', pathId],
    queryFn: async () => {
      const response = await lxpApiListProgress({
        query: { learning_path_id: pathId }
      })
      return response.data ?? []
    },
  })

  const progress = progressData ?? []
  const loading = pathLoading || progressLoading

  if (loading) {
    return (
      <div className="modal-overlay" onClick={onClose}>
        <div className="modal-content" onClick={(e) => e.stopPropagation()}>
          <div className="modal-body">
            <div className="loading">Loading learning path details...</div>
          </div>
        </div>
      </div>
    )
  }

  if (!path) {
    return null
  }

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className="modal-content learning-path-detail-modal" onClick={(e) => e.stopPropagation()}>
        <div className="modal-header">
          <div>
            <h2>{path.title}</h2>
            <span className="subject-badge" style={{ marginTop: '0.5rem' }}>{path.subject_name}</span>
          </div>
          <button className="modal-close" onClick={onClose}>×</button>
        </div>

        <div className="modal-body">
          {/* Path Overview */}
          <div className="path-detail-section">
            <h3>📋 Overview</h3>
            <div className="detail-grid">
              <div className="detail-item">
                <strong>Student:</strong>
                <span>{path.student_name}</span>
              </div>
              <div className="detail-item">
                <strong>Difficulty:</strong>
                <span className="difficulty-badge">{path.difficulty_level}</span>
              </div>
              <div className="detail-item">
                <strong>Start Date:</strong>
                <span>{new Date(path.start_date).toLocaleDateString()}</span>
              </div>
              <div className="detail-item">
                <strong>Target End Date:</strong>
                <span>{new Date(path.target_completion_date).toLocaleDateString()}</span>
              </div>
              <div className="detail-item">
                <strong>Status:</strong>
                <span className={`status-badge ${path.is_active ? 'active' : 'inactive'}`}>
                  {path.is_active ? 'Active' : 'Inactive'}
                </span>
              </div>
              <div className="detail-item">
                <strong>Overall Progress:</strong>
                <span className="completion">{Math.round(path.completion_percentage)}%</span>
              </div>
            </div>

            {path.description && (
              <div className="description-box">
                <strong>Description:</strong>
                <p>{path.description}</p>
              </div>
            )}

            <div className="progress-bar" style={{ marginTop: '1rem' }}>
              <div
                className="progress-fill"
                style={{ width: `${path.completion_percentage}%` }}
              />
            </div>
          </div>

          {/* AI-Generated Goals */}
          {path.personalized_goals && path.personalized_goals.length > 0 && (
            <div className="path-detail-section">
              <h3>🎯 AI-Generated Personalized Goals</h3>
              <div className="goals-grid">
                {path.personalized_goals.map((goal: string, index: number) => (
                  <div key={index} className="goal-card">
                    <span className="goal-number">{index + 1}</span>
                    <span className="goal-text">{goal}</span>
                  </div>
                ))}
              </div>
              <p className="ai-note" style={{ marginTop: '1rem' }}>
                ✨ Generated by Grok AI based on student's grade level, subject, and difficulty
              </p>
            </div>
          )}

          {/* Content Progress */}
          <div className="path-detail-section">
            <h3>📚 Learning Content & Progress</h3>
            {progress.length === 0 ? (
              <div className="empty-state">No content assigned yet</div>
            ) : (
              <div className="content-progress-list">
                {progress.map((item: any) => (
                  <div
                    key={item.id}
                    className="content-progress-item"
                    onClick={() => setSelectedContentId(item.content_id)}
                    style={{ cursor: 'pointer' }}
                  >
                    <div className="content-progress-header">
                      <div>
                        <h4>{item.content_title} 📖</h4>
                        <span className={`status-badge ${item.status}`}>
                          {item.status.replace('_', ' ')}
                        </span>
                      </div>
                      <div className="content-progress-stats">
                        <div className="stat-pill">
                          <span className="stat-label">Completion:</span>
                          <span className="stat-value">{Math.round(item.completion_percentage)}%</span>
                        </div>
                        <div className="stat-pill">
                          <span className="stat-label">Mastery:</span>
                          <span className="stat-value">{Math.round(item.mastery_level)}%</span>
                        </div>
                        {item.time_spent_minutes > 0 && (
                          <div className="stat-pill">
                            <span className="stat-label">Time:</span>
                            <span className="stat-value">{item.time_spent_minutes} min</span>
                          </div>
                        )}
                      </div>
                    </div>
                    <div className="progress-bar small">
                      <div
                        className="progress-fill"
                        style={{ width: `${item.mastery_level}%` }}
                      />
                    </div>
                  </div>
                ))}
              </div>
            )}
          </div>

          {/* Recommended Resources */}
          {path.recommended_resources && path.recommended_resources.length > 0 && (
            <div className="path-detail-section">
              <h3>🔗 Recommended Resources</h3>
              <div className="resources-list">
                {path.recommended_resources.map((resource: any, index: number) => (
                  <a
                    key={index}
                    href={resource.url}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="resource-link"
                  >
                    <span>{resource.title}</span>
                    <span className="resource-type">{resource.type}</span>
                  </a>
                ))}
              </div>
            </div>
          )}
        </div>

        <div className="modal-footer">
          <button className="button-primary" onClick={onClose}>
            Close
          </button>
        </div>
      </div>

      {selectedContentId && (
        <ContentViewerModal
          contentId={selectedContentId}
          studentId={path.student_id}
          learningPathId={pathId}
          progressId={progress.find((p: any) => p.content_id === selectedContentId)?.id}
          onClose={() => setSelectedContentId(null)}
        />
      )}
    </div>
  )
}
